# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CkIinAmqH42y6RaHtkrng9-mku54Tof
"""

!pip install beautifulsoup4

!pip install lxml

from bs4 import BeautifulSoup

!pip install requests

import requests

html_response = requests.get('https://investors.canoo.com/financial-information/cash-flow')
html_text = html_response.text
soup = BeautifulSoup(html_text, 'lxml')

table_of_cash_flow = soup.find('table',class_ = 'report')

print(table_of_cash_flow)

headings1 = table_of_cash_flow.find_all('tr')[0].text
headings2 = table_of_cash_flow.find_all('tr')[1].text
print(headings2)

headings1 = headings1.split('\n')
headings2 = headings2.split('\n')

headings2

headings2 = headings2[1:8]

headings2

s =  table_of_cash_flow.find('strong').text#('tr')[2]#.find('td',class_='p1')#.find('a',class_='a').find('strong').text

print(s)

headings2.insert(0,s)

Cash_flows_operating_activities = table_of_cash_flow.find_all('tr',class_='ro')[0].text

Cash_flows_operating_activities = Cash_flows_operating_activities.split('\n')

Cash_flows_operating_activities = Cash_flows_operating_activities[1:14]

Cash_flows_operating_activities

Cash_flows_operating_activities = [item for item in Cash_flows_operating_activities if item.strip()]
Cash_flows_operating_activities

Cash_flows_operating_activities.append('0')
import csv
csv_file_path = '/content/output.csv'
rows = [headings2, Cash_flows_operating_activities]
# Open the CSV file in write mode
with open(csv_file_path, mode='w', newline='') as csv_file:
    # Create a CSV writer object
    csv_writer = csv.writer(csv_file)
    # Write the rows to the CSV file
    csv_writer.writerows(rows)

print(f'CSV file "{csv_file_path}" created successfully.')

import pandas as pd
df = pd.read_csv('output.csv')
df

Adjustments_to_reconcile_net_loss_to_net_cash_used_operating_activities = [[]]
for i in range(5,20):
    Adjustments_to_reconcile_net_loss_to_net_cash_used_operating_activities.append(table_of_cash_flow.find_all('tr')[i].text.split('\n'))

Adjustments_to_reconcile_net_loss_to_net_cash_used_operating_activities

# Define the item to delete and the item to replace
item_to_delete = ''
item_to_replace = '\xa0'

# Iterate through the list and modify items
for my_list in Adjustments_to_reconcile_net_loss_to_net_cash_used_operating_activities:
  for index, item in enumerate(my_list):
    if item == item_to_delete:
        # Delete the item
        del my_list[index]
    elif item == item_to_replace:
        # Replace the item
        my_list[index] = '0'

Adjustments_to_reconcile_net_loss_to_net_cash_used_operating_activities

Adjustments_to_reconcile_net_loss_to_net_cash_used_operating_activities = Adjustments_to_reconcile_net_loss_to_net_cash_used_operating_activities[1:]

Adjustments_to_reconcile_net_loss_to_net_cash_used_operating_activities.insert(0,headings2)

Adjustments_to_reconcile_net_loss_to_net_cash_used_operating_activities

csv_file_path = '/content/output2.csv'
# Open the CSV file in write mode
with open(csv_file_path, mode='w', newline='') as csv_file:
    # Create a CSV writer object
    csv_writer = csv.writer(csv_file)

    # Write the list of lists to the CSV file
    csv_writer.writerows(Adjustments_to_reconcile_net_loss_to_net_cash_used_operating_activities)

df = pd.read_csv('output2.csv')

df

